name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    container: golang:1.25-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: lint
        run: just lint

      - name: test coverage
        run: just coverage

      - name: upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.txt

  codecov:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: download ci artifacts
        id: download-build-artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: vncsmyrnk/ashttp
          files: artifacts/coverage/coverage.txt
          fail_ci_if_error: true
